Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace MySolution.Module

    Partial Public Class Employee
        Public Sub New()
            Me.Tasks = New List(Of Task)()
        End Sub

        Public Property Id() As Integer
        Public Property FirstName() As String
        Public Property LastName() As String
        Public Property Birthday() As Date?

        Public Overridable Property Tasks() As ICollection(Of Task)
    End Class
End Namespace
