Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace MySolution.Module

    Partial Public Class MyDataModelContainer
        Inherits DbContext

        Public Sub New(ByVal connectionString As String)

            MyBase.New(connectionString)
        End Sub

        Protected Overrides Sub OnModelCreating(ByVal modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub

        Public Overridable Property Employees() As DbSet(Of Employee)
        Public Overridable Property Tasks() As DbSet(Of Task)
    End Class
End Namespace
