'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly: EdmSchemaAttribute()>
#Region "EDM Relationship Metadata"

<Assembly: EdmRelationshipAttribute("MySolutionDataModel", "EmployeeTask", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(MySolution.Module.Employee), "Task", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(MySolution.Module.Task))>

#End Region

Namespace MySolution.Module
    #Region "Contexts"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Partial Public Class MyObjectContext
        Inherits ObjectContext

        #Region "Constructors"

        ''' <summary>
        ''' Initializes a new MyObjectContext object using the connection string found in the 'MyObjectContext' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=MyObjectContext", "MyObjectContext")
            Me.ContextOptions.LazyLoadingEnabled = True
            OnContextCreated()
        End Sub

        ''' <summary>
        ''' Initialize a new MyObjectContext object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "MyObjectContext")
            Me.ContextOptions.LazyLoadingEnabled = True
            OnContextCreated()
        End Sub

        ''' <summary>
        ''' Initialize a new MyObjectContext object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "MyObjectContext")
            Me.ContextOptions.LazyLoadingEnabled = True
            OnContextCreated()
        End Sub

        #End Region

        #Region "Partial Methods"

        Partial Private Sub OnContextCreated()
        End Sub

        #End Region

        #Region "ObjectSet Properties"

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Employees() As ObjectSet(Of Employee)
            Get
                If (_Employees Is Nothing) Then
                    _Employees = MyBase.CreateObjectSet(Of Employee)("Employees")
                End If
                Return _Employees
            End Get
        End Property
        Private _Employees As ObjectSet(Of Employee)

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Tasks() As ObjectSet(Of Task)
            Get
                If (_Tasks Is Nothing) Then
                    _Tasks = MyBase.CreateObjectSet(Of Task)("Tasks")
                End If
                Return _Tasks
            End Get
        End Property
        Private _Tasks As ObjectSet(Of Task)

        #End Region

        #Region "AddTo Methods"

        ''' <summary>
        ''' Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        ''' </summary>
        Public Sub AddToEmployees(ByVal _employee As Employee)
            MyBase.AddObject("Employees", _employee)
        End Sub

        ''' <summary>
        ''' Deprecated Method for adding a new object to the Tasks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        ''' </summary>
        Public Sub AddToTasks(ByVal _task As Task)
            MyBase.AddObject("Tasks", _task)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entities"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="MySolutionDataModel", Name:="Employee"), Serializable(), DataContractAttribute(IsReference:=True)> _
    Partial Public Class Employee
        Inherits EntityObject

        #Region "Factory Method"

        ''' <summary>
        ''' Create a new Employee object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        Public Shared Function CreateEmployee(ByVal id As Global.System.Int32) As Employee
            Dim _employee As New Employee()
            _employee.Id = id
            Return _employee
        End Function

        #End Region

        #Region "Primitive Properties"

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
        Public Property Id() As Global.System.Int32
            Get
                Return _Id
            End Get
            Protected Set(ByVal value As System.Int32)
                If _Id <> value Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
        Private _Id As Global.System.Int32
        Partial Private Sub OnIdChanging(ByVal value As Global.System.Int32)
        End Sub
        Partial Private Sub OnIdChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
        Public Property FirstName() As Global.System.String
            Get
                Return _FirstName
            End Get
            Set(ByVal value As System.String)
                OnFirstNameChanging(value)
                ReportPropertyChanging("FirstName")
                _FirstName = StructuralObject.SetValidValue(value, True)
                ReportPropertyChanged("FirstName")
                OnFirstNameChanged()
            End Set
        End Property
        Private _FirstName As Global.System.String
        Partial Private Sub OnFirstNameChanging(ByVal value As Global.System.String)
        End Sub
        Partial Private Sub OnFirstNameChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
        Public Property LastName() As Global.System.String
            Get
                Return _LastName
            End Get
            Set(ByVal value As System.String)
                OnLastNameChanging(value)
                ReportPropertyChanging("LastName")
                _LastName = StructuralObject.SetValidValue(value, True)
                ReportPropertyChanged("LastName")
                OnLastNameChanged()
            End Set
        End Property
        Private _LastName As Global.System.String
        Partial Private Sub OnLastNameChanging(ByVal value As Global.System.String)
        End Sub
        Partial Private Sub OnLastNameChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
        Public Property Birhtday() As Global.System.DateTime?
            Get
                Return _Birhtday
            End Get
            Set(ByVal value? As Date)
                OnBirhtdayChanging(value)
                ReportPropertyChanging("Birhtday")
                _Birhtday = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Birhtday")
                OnBirhtdayChanged()
            End Set
        End Property
        Private _Birhtday? As Global.System.DateTime
        Partial Private Sub OnBirhtdayChanging(ByVal value? As Global.System.DateTime)
        End Sub
        Partial Private Sub OnBirhtdayChanged()
        End Sub

        #End Region


        #Region "Navigation Properties"

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute(), SoapIgnoreAttribute(), DataMemberAttribute(), EdmRelationshipNavigationPropertyAttribute("MySolutionDataModel", "EmployeeTask", "Task")> _
        Public Property Tasks() As EntityCollection(Of Task)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Task)("MySolutionDataModel.EmployeeTask", "Task")
            End Get
            Set(ByVal value As EntityCollection(Of Task))
                If (value IsNot Nothing) Then
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Task)("MySolutionDataModel.EmployeeTask", "Task", value)
                End If
            End Set
        End Property

        #End Region

    End Class

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="MySolutionDataModel", Name:="Task"), Serializable(), DataContractAttribute(IsReference:=True)> _
    Partial Public Class Task
        Inherits EntityObject

        #Region "Factory Method"

        ''' <summary>
        ''' Create a new Task object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        Public Shared Function CreateTask(ByVal id As Global.System.Int32) As Task
            Dim _task As New Task()
            _task.Id = id
            Return _task
        End Function

        #End Region

        #Region "Primitive Properties"

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
        Public Property Id() As Global.System.Int32
            Get
                Return _Id
            End Get
            Set(ByVal value As System.Int32)
                If _Id <> value Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
        Private _Id As Global.System.Int32
        Partial Private Sub OnIdChanging(ByVal value As Global.System.Int32)
        End Sub
        Partial Private Sub OnIdChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
        Public Property Subject() As Global.System.String
            Get
                Return _Subject
            End Get
            Set(ByVal value As System.String)
                OnSubjectChanging(value)
                ReportPropertyChanging("Subject")
                _Subject = StructuralObject.SetValidValue(value, True)
                ReportPropertyChanged("Subject")
                OnSubjectChanged()
            End Set
        End Property
        Private _Subject As Global.System.String
        Partial Private Sub OnSubjectChanging(ByVal value As Global.System.String)
        End Sub
        Partial Private Sub OnSubjectChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
        Public Property Description() As Global.System.String
            Get
                Return _Description
            End Get
            Set(ByVal value As System.String)
                OnDescriptionChanging(value)
                ReportPropertyChanging("Description")
                _Description = StructuralObject.SetValidValue(value, True)
                ReportPropertyChanged("Description")
                OnDescriptionChanged()
            End Set
        End Property
        Private _Description As Global.System.String
        Partial Private Sub OnDescriptionChanging(ByVal value As Global.System.String)
        End Sub
        Partial Private Sub OnDescriptionChanged()
        End Sub

        #End Region


        #Region "Navigation Properties"

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute(), SoapIgnoreAttribute(), DataMemberAttribute(), EdmRelationshipNavigationPropertyAttribute("MySolutionDataModel", "EmployeeTask", "Employee")> _
        Public Property Employee() As Employee
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Employee)("MySolutionDataModel.EmployeeTask", "Employee").Value
            End Get
            Set(ByVal value As Employee)
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Employee)("MySolutionDataModel.EmployeeTask", "Employee").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False), DataMemberAttribute()> _
        Public Property EmployeeReference() As EntityReference(Of Employee)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Employee)("MySolutionDataModel.EmployeeTask", "Employee")
            End Get
            Set(ByVal value As EntityReference(Of Employee))
                If (value IsNot Nothing) Then
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Employee)("MySolutionDataModel.EmployeeTask", "Employee", value)
                End If
            End Set
        End Property

        #End Region

    End Class

    #End Region


End Namespace
