Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace MySolution.Module

    Partial Public Class Task
        Public Property Id() As Integer
        Public Property Subject() As String
        Public Property Description() As String

        Public Overridable Property Employee() As Employee
    End Class
End Namespace
