'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee

    Private _Id As Integer
    Public Property Id As Integer
        Get
            Return _Id
        End Get
        Set(ByVal value As Integer)
            If (Not Equals(_Id,value))
				_Id = value
				OnIdChanged()
			End If
        End Set
    End Property
    Private Partial Sub OnIdChanged()
    End Sub


    Private _FirstName As String
    Public Property FirstName As String
        Get
            Return _FirstName
        End Get
        Set(ByVal value As String)
            If (Not Equals(_FirstName,value))
				_FirstName = value
				OnFirstNameChanged()
			End If
        End Set
    End Property
    Private Partial Sub OnFirstNameChanged()
    End Sub


    Private _LastName As String
    Public Property LastName As String
        Get
            Return _LastName
        End Get
        Set(ByVal value As String)
            If (Not Equals(_LastName,value))
				_LastName = value
				OnLastNameChanged()
			End If
        End Set
    End Property
    Private Partial Sub OnLastNameChanged()
    End Sub


    Private _Birthday As Date
    Public Property Birthday As Date
        Get
            Return _Birthday
        End Get
        Set(ByVal value As Date)
            If (Not Equals(_Birthday,value))
				_Birthday = value
				OnBirthdayChanged()
			End If
        End Set
    End Property
    Private Partial Sub OnBirthdayChanged()
    End Sub


    Public Overridable Property Task As ICollection(Of Task) = New List(Of Task)

End Class
