'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class MySolutionModelContainer
    Inherits DbContext

    Public Sub New(connectionString As String)
        MyBase.New(connectionString)
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ModulesInfo() As DbSet(Of XafModuleInfo)
    Public Overridable Property EmployeeSet() As DbSet(Of Employee)
    Public Overridable Property TaskSet() As DbSet(Of Task)

End Class
