'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Task

    Private _Id As Integer
    Public Property Id As Integer
        Get
            Return _Id
        End Get
        Set(ByVal value As Integer)
            If (Not Equals(_Id,value))
				_Id = value
				OnIdChanged()
			End If
        End Set
    End Property
    Private Partial Sub OnIdChanged()
    End Sub


    Private _Subject As String
    Public Property Subject As String
        Get
            Return _Subject
        End Get
        Set(ByVal value As String)
            If (Not Equals(_Subject,value))
				_Subject = value
				OnSubjectChanged()
			End If
        End Set
    End Property
    Private Partial Sub OnSubjectChanged()
    End Sub


    Private _Description As String
    Public Property Description As String
        Get
            Return _Description
        End Get
        Set(ByVal value As String)
            If (Not Equals(_Description,value))
				_Description = value
				OnDescriptionChanged()
			End If
        End Set
    End Property
    Private Partial Sub OnDescriptionChanged()
    End Sub


    Public Overridable Property Employee As Employee

End Class
