'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XafModuleInfo

    Private _ID As Integer
    Public Property ID As Integer
        Get
            Return _ID
        End Get
        Protected Set(ByVal value As Integer)
            If (Not Equals(_ID,value))
				_ID = value
				OnIDChanged()
			End If
        End Set
    End Property
    Private Partial Sub OnIDChanged()
    End Sub


    Private _Name As String
    Public Property Name As String
        Get
            Return _Name
        End Get
        Set(ByVal value As String)
            If (Not Equals(_Name,value))
				_Name = value
				OnNameChanged()
			End If
        End Set
    End Property
    Private Partial Sub OnNameChanged()
    End Sub


    Private _Version As String
    Public Property Version As String
        Get
            Return _Version
        End Get
        Set(ByVal value As String)
            If (Not Equals(_Version,value))
				_Version = value
				OnVersionChanged()
			End If
        End Set
    End Property
    Private Partial Sub OnVersionChanged()
    End Sub


    Private _AssemblyFileName As String
    Public Property AssemblyFileName As String
        Get
            Return _AssemblyFileName
        End Get
        Set(ByVal value As String)
            If (Not Equals(_AssemblyFileName,value))
				_AssemblyFileName = value
				OnAssemblyFileNameChanged()
			End If
        End Set
    End Property
    Private Partial Sub OnAssemblyFileNameChanged()
    End Sub


    Private _IsMain As Boolean
    Public Property IsMain As Boolean
        Get
            Return _IsMain
        End Get
        Set(ByVal value As Boolean)
            If (Not Equals(_IsMain,value))
				_IsMain = value
				OnIsMainChanged()
			End If
        End Set
    End Property
    Private Partial Sub OnIsMainChanged()
    End Sub


End Class
