//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySolution.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Task = new List<Task>();
        }
    
        private int _id;
    	public int Id 
    	{ 
    		get { return _id; } 
    		set
    		{
    			if (value != _id) {
    				_id = value;
    				 OnIdChanged();
    			}
    		} 
    	}
    	partial void OnIdChanged(); 
    
        private string _firstName;
    	public string FirstName 
    	{ 
    		get { return _firstName; } 
    		set
    		{
    			if (value != _firstName) {
    				_firstName = value;
    				 OnFirstNameChanged();
    			}
    		} 
    	}
    	partial void OnFirstNameChanged(); 
    
        private string _lastName;
    	public string LastName 
    	{ 
    		get { return _lastName; } 
    		set
    		{
    			if (value != _lastName) {
    				_lastName = value;
    				 OnLastNameChanged();
    			}
    		} 
    	}
    	partial void OnLastNameChanged(); 
    
        private System.DateTime _birthday;
    	public System.DateTime Birthday 
    	{ 
    		get { return _birthday; } 
    		set
    		{
    			if (value != _birthday) {
    				_birthday = value;
    				 OnBirthdayChanged();
    			}
    		} 
    	}
    	partial void OnBirthdayChanged(); 
    
    
        public virtual ICollection<Task> Task { get; set; }
    }
}
