//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySolution.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        private int _id;
    	public int Id 
    	{ 
    		get { return _id; } 
    		set
    		{
    			if (value != _id) {
    				_id = value;
    				 OnIdChanged();
    			}
    		} 
    	}
    	partial void OnIdChanged(); 
    
        private string _subject;
    	public string Subject 
    	{ 
    		get { return _subject; } 
    		set
    		{
    			if (value != _subject) {
    				_subject = value;
    				 OnSubjectChanged();
    			}
    		} 
    	}
    	partial void OnSubjectChanged(); 
    
        private string _description;
    	public string Description 
    	{ 
    		get { return _description; } 
    		set
    		{
    			if (value != _description) {
    				_description = value;
    				 OnDescriptionChanged();
    			}
    		} 
    	}
    	partial void OnDescriptionChanged(); 
    
    
        public virtual Employee Employee { get; set; }
    }
}
